using FarmManagement.Web.Data;
using FarmManagement.Web.Models.Enums;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FarmManagement.AnalyticsService.Controllers;

[ApiController]
[Route("api/analytics")]
[Authorize]
public class AnalyticsController : ControllerBase
{
    private readonly FarmDbContext _db;
    public AnalyticsController(FarmDbContext db) => _db = db;

    /// <summary>Get the farm-wide dashboard summary (counts, totals).</summary>
    [HttpGet("dashboard")]
    public async Task<IActionResult> Dashboard()
    {
        var totalYield = await _db.Harvests.SumAsync(h => (decimal?)h.ActualYieldKg) ?? 0;
        return Ok(new
        {
            TotalFields        = await _db.Fields.CountAsync(),
            TotalCrops         = await _db.Crops.CountAsync(),
            TotalSchedules     = await _db.PlantingSchedules.CountAsync(),
            TotalHarvests      = await _db.Harvests.CountAsync(),
            TotalPestIncidents = await _db.PestIncidents.CountAsync(),
            ActivePests        = await _db.PestIncidents.CountAsync(p => p.Status == IncidentStatus.Active),
            TotalResources     = await _db.Resources.CountAsync(r => r.Type != ResourceType.Pesticide),
            LowStockResources  = await _db.Resources.CountAsync(r => r.Quantity <= 10 && r.Type != ResourceType.Pesticide),
            TotalYieldKg       = totalYield,
            UpcomingHarvests   = await _db.PlantingSchedules.CountAsync(s =>
                s.Status == "Scheduled" &&
                s.ScheduledDate >= DateTime.Today &&
                s.ScheduledDate <= DateTime.Today.AddDays(30))
        });
    }

    /// <summary>Get yield analytics — all harvests with crop/field info.</summary>
    [HttpGet("yield")]
    public async Task<IActionResult> Yield()
    {
        var records = await _db.Harvests.AsNoTracking()
            .Include(h => h.PlantingSchedule).ThenInclude(ps => ps.Crop)
            .Include(h => h.PlantingSchedule).ThenInclude(ps => ps.Field)
            .OrderByDescending(h => h.HarvestedDate)
            .ToListAsync();

        return Ok(new
        {
            TotalYield   = records.Sum(r => r.ActualYieldKg),
            AverageYield = records.Count > 0 ? records.Average(r => r.ActualYieldKg) : 0,
            HarvestCount = records.Count,
            Records      = records.Select(r => new
            {
                r.HarvestId,
                CropName  = r.PlantingSchedule?.Crop?.CropName,
                FieldName = r.PlantingSchedule?.Field?.FieldName,
                r.HarvestedDate,
                r.ActualYieldKg,
                r.Notes
            })
        });
    }

    /// <summary>Get pest summary — counts by status and breakdown by crop.</summary>
    [HttpGet("pest-summary")]
    public async Task<IActionResult> PestSummary()
    {
        var incidents = await _db.PestIncidents.Include(p => p.Crop).AsNoTracking().ToListAsync();
        return Ok(new
        {
            Total      = incidents.Count,
            Active     = incidents.Count(p => p.Status == IncidentStatus.Active),
            Monitoring = incidents.Count(p => p.Status == IncidentStatus.Monitoring),
            Resolved   = incidents.Count(p => p.Status == IncidentStatus.Resolved),
            ByCrop     = incidents
                .GroupBy(p => p.Crop?.CropName ?? "Unknown")
                .Select(g => new
                {
                    Crop       = g.Key,
                    Active     = g.Count(p => p.Status == IncidentStatus.Active),
                    Monitoring = g.Count(p => p.Status == IncidentStatus.Monitoring),
                    Resolved   = g.Count(p => p.Status == IncidentStatus.Resolved)
                })
        });
    }

    /// <summary>Get resource inventory report — type breakdown and low-stock items.</summary>
    [HttpGet("resource-report")]
    public async Task<IActionResult> ResourceReport()
    {
        var resources = await _db.Resources.AsNoTracking()
            .Where(r => r.Type != ResourceType.Pesticide)
            .Include(r => r.ResourceUsages)
            .ToListAsync();

        return Ok(new
        {
            Total         = resources.Count,
            LowStockCount = resources.Count(r => r.Quantity <= 10),
            ByType        = resources
                .GroupBy(r => r.Type.ToString())
                .Select(g => new { Type = g.Key, Count = g.Count(), TotalQuantity = g.Sum(r => r.Quantity) }),
            LowStockItems = resources
                .Where(r => r.Quantity <= 10)
                .Select(r => new { r.ResourceId, r.Name, r.Quantity, r.Unit, r.Type })
        });
    }

    /// <summary>Get yield reports generated by the system.</summary>
    [HttpGet("yield-reports")]
    public async Task<IActionResult> YieldReports()
        => Ok(await _db.YieldReports.Include(y => y.Crop).AsNoTracking()
                       .OrderByDescending(y => y.GeneratedAt).ToListAsync());
}
