services:
  api:
    build:
      context: ./EnergyPulse
      dockerfile: Dockerfile
    container_name: energypulse-api
    ports:
      - "5015:5015"
    environment:
      ConnectionStrings__DefaultConnection: "Data Source=/app/data/EnergyPulse.db"
      JwtSettings__Secret: "@SrinivasDevelopFirstApplication"
      JwtSettings__Issuer: "EnergyPulseAPI"
      JwtSettings__Audience: "EnergyPulseUI"
      JwtSettings__ExpiryMinutes: "60"
    volumes:
      - sqlite_data:/app/data
    networks:
      - energypulse_network

  ui:
    build:
      context: ./EnergyPulse.UI
      dockerfile: Dockerfile
    container_name: energypulse-ui
    ports:
      - "5241:80"
    depends_on:
      - api
    networks:
      - energypulse_network

volumes:
  sqlite_data:

networks:
  energypulse_network: