// <auto-generated />
using System;
using FarmManagement.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FarmManagement.Web.Migrations
{
    [DbContext(typeof(FarmDbContext))]
    [Migration("20260505054945_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FarmManagement.Web.Models.Entities.ActivityLog", b =>
                {
                    b.Property<int>("ActivityLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActivityLogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ActivityLogId");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("FarmManagement.Web.Models.Entities.AppUser", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHint")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasDefaultValue("");

                    b.Property<int>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("FarmManagement.Web.Models.Entities.Crop", b =>
                {
                    b.Property<int>("CropId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CropId"));

                    b.Property<string>("CropName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CropType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ExpectedHarvestDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FieldId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PlantingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Season")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CropId");

                    b.HasIndex("FieldId");

                    b.ToTable("Crops");
                });

            modelBuilder.Entity("FarmManagement.Web.Models.Entities.Field", b =>
                {
                    b.Property<int>("FieldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FieldId"));

                    b.Property<decimal>("AreaHectares")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SoilType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("FieldId");

                    b.ToTable("Fields");
                });

            modelBuilder.Entity("FarmManagement.Web.Models.Entities.Harvest", b =>
                {
                    b.Property<int>("HarvestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HarvestId"));

                    b.Property<decimal>("ActualYieldKg")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("HarvestedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int");

                    b.HasKey("HarvestId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("Harvests");
                });

            modelBuilder.Entity("FarmManagement.Web.Models.Entities.PestIncident", b =>
                {
                    b.Property<int>("PestIncidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PestIncidentId"));

                    b.Property<int>("CropId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DiseaseName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PestName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ReportedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("PestIncidentId");

                    b.HasIndex("CropId");

                    b.ToTable("PestIncidents");
                });

            modelBuilder.Entity("FarmManagement.Web.Models.Entities.PlantingSchedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleId"));

                    b.Property<int>("CropId")
                        .HasColumnType("int");

                    b.Property<decimal>("ExpectedYieldKg")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("FieldId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ScheduleId");

                    b.HasIndex("CropId");

                    b.HasIndex("FieldId");

                    b.ToTable("PlantingSchedules");
                });

            modelBuilder.Entity("FarmManagement.Web.Models.Entities.Resource", b =>
                {
                    b.Property<int>("ResourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResourceId"));

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("PestIncidentId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ResourceId");

                    b.HasIndex("PestIncidentId");

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("FarmManagement.Web.Models.Entities.ResourceUsage", b =>
                {
                    b.Property<int>("ResourceUsageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResourceUsageId"));

                    b.Property<int?>("FieldId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("QuantityUsed")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ResourceId")
                        .HasColumnType("int");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UsedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ResourceUsageId");

                    b.HasIndex("FieldId");

                    b.HasIndex("ResourceId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("ResourceUsages");
                });

            modelBuilder.Entity("FarmManagement.Web.Models.Entities.YieldReport", b =>
                {
                    b.Property<int>("YieldReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("YieldReportId"));

                    b.Property<decimal>("AverageYieldPerAcre")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("CropId")
                        .HasColumnType("int");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarks")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Season")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalYieldKg")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("YieldReportId");

                    b.HasIndex("CropId");

                    b.ToTable("YieldReports");
                });

            modelBuilder.Entity("FarmManagement.Web.Models.Entities.Crop", b =>
                {
                    b.HasOne("FarmManagement.Web.Models.Entities.Field", "Field")
                        .WithMany("Crops")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Field");
                });

            modelBuilder.Entity("FarmManagement.Web.Models.Entities.Harvest", b =>
                {
                    b.HasOne("FarmManagement.Web.Models.Entities.PlantingSchedule", "PlantingSchedule")
                        .WithMany("Harvests")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlantingSchedule");
                });

            modelBuilder.Entity("FarmManagement.Web.Models.Entities.PestIncident", b =>
                {
                    b.HasOne("FarmManagement.Web.Models.Entities.Crop", "Crop")
                        .WithMany("PestIncidents")
                        .HasForeignKey("CropId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Crop");
                });

            modelBuilder.Entity("FarmManagement.Web.Models.Entities.PlantingSchedule", b =>
                {
                    b.HasOne("FarmManagement.Web.Models.Entities.Crop", "Crop")
                        .WithMany("PlantingSchedules")
                        .HasForeignKey("CropId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FarmManagement.Web.Models.Entities.Field", "Field")
                        .WithMany("PlantingSchedules")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Crop");

                    b.Navigation("Field");
                });

            modelBuilder.Entity("FarmManagement.Web.Models.Entities.Resource", b =>
                {
                    b.HasOne("FarmManagement.Web.Models.Entities.PestIncident", "PestIncident")
                        .WithMany("Resources")
                        .HasForeignKey("PestIncidentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PestIncident");
                });

            modelBuilder.Entity("FarmManagement.Web.Models.Entities.ResourceUsage", b =>
                {
                    b.HasOne("FarmManagement.Web.Models.Entities.Field", null)
                        .WithMany("ResourceUsages")
                        .HasForeignKey("FieldId");

                    b.HasOne("FarmManagement.Web.Models.Entities.Resource", "Resource")
                        .WithMany("ResourceUsages")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FarmManagement.Web.Models.Entities.PlantingSchedule", "PlantingSchedule")
                        .WithMany("ResourceUsages")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PlantingSchedule");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("FarmManagement.Web.Models.Entities.YieldReport", b =>
                {
                    b.HasOne("FarmManagement.Web.Models.Entities.Crop", "Crop")
                        .WithMany("YieldReports")
                        .HasForeignKey("CropId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Crop");
                });

            modelBuilder.Entity("FarmManagement.Web.Models.Entities.Crop", b =>
                {
                    b.Navigation("PestIncidents");

                    b.Navigation("PlantingSchedules");

                    b.Navigation("YieldReports");
                });

            modelBuilder.Entity("FarmManagement.Web.Models.Entities.Field", b =>
                {
                    b.Navigation("Crops");

                    b.Navigation("PlantingSchedules");

                    b.Navigation("ResourceUsages");
                });

            modelBuilder.Entity("FarmManagement.Web.Models.Entities.PestIncident", b =>
                {
                    b.Navigation("Resources");
                });

            modelBuilder.Entity("FarmManagement.Web.Models.Entities.PlantingSchedule", b =>
                {
                    b.Navigation("Harvests");

                    b.Navigation("ResourceUsages");
                });

            modelBuilder.Entity("FarmManagement.Web.Models.Entities.Resource", b =>
                {
                    b.Navigation("ResourceUsages");
                });
#pragma warning restore 612, 618
        }
    }
}
